language: rust
matrix:
    fast_finish: true
    include:
        - rust: nightly
          env: FEATURES="--features nightly"
        - rust: beta
        - rust: stable

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - ./.travis/readme.py
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'for f in ./doc/**/*.md; do echo "Running rustdoc on $f"; rustdoc -L ./target/debug -L ./target/debug/deps --test $f;  done'
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then for f in ./benches/*.rs; do cargo test --bench $(basename $f .rs) $FEATURES; done; fi'

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev


after_success:
  - '[ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/hyper-*'
  - echo "$TRAVIS_PULL_REQUEST"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - '[ $TRAVIS_PULL_REQUEST = false ] &&
    { [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]; } &&
    ./.travis/docs.sh &&
    echo "\nDocs published.\n"'

env:
    global:
        - secure: bcrNns6QyPdm/2eQtgnjX0PrNgo1GsfMOo8+ReI0jhwGEK5s3lwMvEN3pxgseEEWWzcXbScBy9OsVAHQ34zC5ENOLBlP3Gpc8FTgWoNrzVxNte/2mrnaNb+hLsXS8j8rGtXA0kpe/Z6poqsqoHiGZv6SSnm/vPUr6GSC6uiIO0U=

notifications:
    email: false
