language: rust
#sudo: true # Required for functional IPv6 (forces VM instead of Docker).
dist: trusty
matrix:
    fast_finish: true
    include:
        - rust: nightly
          env: FEATURES="--no-default-features --features runtime,nightly"
        # Dependencies may be using the unstable `async_await` feature for now...
        #- rust: beta
        #  env: FEATURES="--no-default-features --features runtime,__internal_happy_eyeballs_tests"
        #- rust: stable
        #  env: FEATURES="--no-default-features --features runtime,__internal_happy_eyeballs_tests"
        #- rust: stable
        #  env: FEATURES="--no-default-features"
        # Minimum Supported Rust Version
        #- rust: 1.36.0
        #  env: FEATURES="--no-default-features --features runtime" BUILD_ONLY="1"

#before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/83
  #- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
  #    sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
  #  fi

script:
  - cargo build $FEATURES --all-targets
  # Disable tests temporarily
  # - 'if [ "$BUILD_ONLY" != "1" ]; then cargo test $FEATURES -- --test-threads=1; fi'
  # - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then for f in ./benches/*.rs; do cargo test --bench $(basename $f .rs) $FEATURES; done; fi'

env:
    global:
        - RUST_BACKTRACE=1
        - secure: KipdEhZsGIrb2W0HsDbC95x8FJ1RKEWPq8uSK8wSZwGw6MtvoZDX0edfrtf4o3/skA0h84yn35ZWF/rpo1ZEesgFY1g+l+me+jtyGvMwEsXTGjNP4oNR2MrDizjO8eYDm4hRUCLEmJVvsq4j7oNVdLGHfdrcnwqk8/NxJsRzqXM=
